### PR TITLE
Adding some puns 😏

### PR DESCRIPTION
**Pull request by jmannfeld**

### CODE REVIEW

**Comment by AlexLakatos** [comment]
Thanks for the PR! The bugs pun is already there, but I love the byte pun. Can you remove the bugs pun, please?

**Comment by jmannfeld** [comment]
Whoops! Yep, I just removed that bugs pun. Thank you!

**Comment by jmannfeld** [comment]
Any way this could get accepted today? 😁

**Comment by AlexLakatos** [comment]
Sure. Thanks for the changes. It still counts for Hacktoberfest, it was opened in October. Sorry for not merging yesterday.

**Comment by jmannfeld** [comment]
Gotcha, no problem. Thank you!

**Pull request merged**
