### PR TITLE
Update puns.json

### PR DESCRIPTION
**Pull request by NexWeb**

### CODE REVIEW

**Comment by AlexLakatos** [comment]
Thanks for the PR! This one wasn't that funny, so I'm not going to merge it. But I know you can pun better, so I'll look out for your next PR.

**Comment by TomGranot** [comment]
It wasn't that bad actually @AlexLakatos ;) kinda on the milder side

**Comment by AlexLakatos** [comment]
In retrospect, I'm still having Dijkstra flashbacks from college ;)

**Comment by NexWeb** [comment]
IMO there are several that are less funny. You should consider the time someone took to contribute a gift.

**Comment by TomGranot** [comment]
@AlexLakatos he is a constant figure. A professor of mine had a slide with his image before teaching us the shortest path algo, and he took like 5 minutes to tell the story about the train station, and how the idea came up to him out of the blue. It was a really nice moment, and I was half expecting the prof to follow up with a meme afterwards since it felt more like a tech talk than a class.

Bitterly disappointed.

**Pull request closed without merging**
